[project]
name = "acpg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "basedpyright>=1.29.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = 'off'
